version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
  reviewers:
  - gdarb
