# https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

zstyle ':completion:*' menu select

export HISTFILE=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/histfile
export HISTSIZE=1000
export SAVEHIST=1000

setopt appendhistory autocd beep extendedglob nomatch notify
bindkey -v
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit -d ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zcompdump

# make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# enable starship prompt
if type starship &>/dev/null; then
    eval "$(starship init zsh)"
fi
