name: CI

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    bootstrap:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install formulae
              run: |
                  export HOMEBREW_NO_AUTO_UPDATE=1
                  brew install bat exa fish jump neovim ripgrep rustup starship vim vivid

            - name: Run `bootstrap`
              run: ./scripts/bootstrap

            - name: Run `config.fish`
              run: fish fish/config.fish
